### ISSUE TITLE
Add links to the marketplace page

### ISSUE THREAD

**Issue by DavidDeSloovere** [tylermurry/ado-pr-auto-comment#3]
Links to this repo are missing on https://marketplace.visualstudio.com/items?itemName=tylermurry.pr-auto-comment
Is handy for reporting issues, starring the project, etc...

**Comment by tylermurry** [comment]
Great point! I have updated the readme accordingly.

Thanks!

**Comment by DavidDeSloovere** [comment]
I actually meant to other way. One the page that's displayed on the visualstudio site, there is no link to this repo on github.
